<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta content=\"IE=edge\" http-equiv=\"X-UA-Compatible\">\n";
echo "    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n";
echo "    <link crossorigin=\"anonymous\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\n";
echo "          integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" rel=\"stylesheet\">\n";
echo "    <link href=\"https://fonts.googleapis.com\" rel=\"preconnect\">\n";
echo "    <link crossorigin href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap\" rel=\"stylesheet\">\n";
echo "    <title>Document</title>\n";
echo "    <link href=\"contribute-page.css\" rel=\"stylesheet\"/>\n";
echo "    <script src=\"contribute-page.js\"></script>\n";
echo "</head>\n";
echo "<body class=\"vh-100\">\n";
echo "<div class=\"container-fluid\">\n";
echo "    <div class=\"container\">\n";
echo "        <header class=\"col-lg-12 mt-3 py-1 resize43\" style=\"margin-bottom: 90px;\">\n";
echo "            <div class=\"header-wrapper\">\n";
echo "                <div class=\"main\">\n";
echo "                    <h2 class=\"title\">Contribute to</h2>\n";
echo "                    <div class=\"bounce-line bounce-first\"></div>\n";
echo "                    <div class=\"bounce-line bounce-second\"></div>\n";
echo "                    <div class=\"bounce-line bounce-third delete768\"></div>\n";
echo "                    <div class=\"bounce-line bounce-fourth delete992\"></div>\n";
echo "                    <div class=\"logo\">\n";
echo "                        <img alt=\"bu-logo\" class=\"delete992\" src=\"https://s4yt.building-u.com/storage/27/BUlogo.png\">\n";
echo "                    </div>\n";
echo "                    <div class=\"holder holder-one holder-clockwise holder-first-row delete992\"></div>\n";
echo "                    <div class=\"holder holder-two holder-counter-clockwise holder-second-row\"></div>\n";
echo "                    <div class=\"holder holder-three holder-clockwise holder-second-row\"></div>\n";
echo "                    <div class=\"logo\">\n";
echo "                        <img alt=\"bu-logo\" class=\"delete768\"\n";
echo "                             src=\"https://s4yt.building-u.com/storage/27/BUlogo.png\"\n";
echo "                             style=\"transform: rotate(25deg) translateX(-100px) translateY(100px);\">\n";
echo "                    </div>\n";
echo "                    <div class=\"logo\">\n";
echo "                        <img alt=\"bu-logo\"\n";
echo "                             src=\"https://s4yt.building-u.com/storage/27/BUlogo.png\"\n";
echo "                             style=\"transform: rotate(25deg) translateX(-277px) translateY(42px);\">\n";
echo "                    </div>\n";
echo "                    <div class=\"holder holder-four holder-counter-clockwise holder-second-row delete768\"></div>\n";
echo "                    <div class=\"holder holder-five holder-clockwise holder-second-row delete992\"></div>\n";
echo "                    <div class=\"holder holder-six holder-counter-clockwise holder-second-row delete992\"></div>\n";
echo "                    <div class=\"holder holder-seven holder-clockwise holder-second-row delete1200\"></div>\n";
echo "                    <div class=\"holder holder-eight holder-counter-clockwise holder-first-row delete1200\"></div>\n";
echo "                </div>\n";
echo "                <div class=\"overlay\">\n";
echo "                    <h2 class=\"title col-lg-12\">Explore the U-Shop</h2>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </header>\n";
echo "        <!-- STEPS -->\n";
echo "        <div class=\"row mt-3 mb-3\">\n";
echo "            <div class=\"col-lg-4 info resize40vh gutter1rem delete992\" style=\"margin-bottom: 30px\">\n";
echo "                <div class=\"info-wrapper\">\n";
echo "                    <center><h2 class=\"title mb-5\">U-steps</h2><span\n";
echo "                            class=\"subtitle text-white fw-bold col-lg-10 offset-lg-1 text-center mt-5\"\n";
echo "                            style=\"margin: 0;\">\n";
echo "              To use rewards at the U-SHOP <br></center>\n";
echo "                    <div class=\"row\" style=\"margin-top: 75px;\">\n";
echo "                        <div class=\"col-lg-12\">\n";
echo "                            <ul class=\"step-list\">\n";
echo "                                <li class=\"step-item\">\n";
echo "                                    <div class=\"row\">\n";
echo "                                        <div class=\"step-number\">\n";
echo "                                            <span class=\"step-number-content\">1</span>\n";
echo "                                        </div>\n";
echo "                                        <div class=\"icon col-lg-2\">\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <div class=\"step col-lg-6\">\n";
echo "                                            <p class=\"instructions\">Tell us who to thank and select an amount of\n";
echo "                                                support.</p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </li>\n";
echo "                                <li class=\"step-item\" style=\"margin-top: 55px\">\n";
echo "                                    <div class=\"row\">\n";
echo "                                        <div class=\"step-number\">\n";
echo "                                            <span class=\"step-number-content\">2</span>\n";
echo "                                        </div>\n";
echo "                                        <div class=\"icon col-lg-2\">\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <div class=\"step col-lg-6\">\n";
echo "                                            <p class=\"instructions\">Choose what U would like to support.</p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </li>\n";
echo "                                <li class=\"step-item\" style=\"margin-top: 50px;\">\n";
echo "                                    <div class=\"row\">\n";
echo "                                        <div class=\"step-number\">\n";
echo "                                            <span class=\"step-number-content\">3</span>\n";
echo "                                        </div>\n";
echo "                                        <div class=\"icon col-lg-2\">\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <div class=\"step col-lg-6\">\n";
echo "                                            <p class=\"instructions\">Enter your card details! </p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </li>\n";
echo "                                <li class=\"step-item\" style=\"margin-top: 50px;\">\n";
echo "                                    <div class=\"row\">\n";
echo "                                        <div class=\"step-number\">\n";
echo "                                            <span class=\"step-number-content\">4</span>\n";
echo "                                        </div>\n";
echo "                                        <div class=\"icon col-lg-2\">\n";
echo "\n";
echo "                                        </div>\n";
echo "                                        <div class=\"step col-lg-6\">\n";
echo "                                            <p class=\"instructions\">Select if you would like to give your ThankUpointz\n";
echo "                                                to someone.\n";
echo "                                            </p>\n";
echo "                                        </div>\n";
echo "                                    </div>\n";
echo "                                </li>\n";
echo "                                <li class=\"step-item\" style=\"margin-top: 50px;\">\n";
echo "                                    <div style=\"align-content: center;\">\n";
echo "                                        <p class=\"instructions\" style=\"margin-left: 30px; width:80%;\">After submitting\n";
echo "                                            you or your recipient will recieve ThankUpointz and you will be allowed to\n";
echo "                                            use these in the U-Shop\n";
echo "                                        </p>\n";
echo "                                    </div>\n";
echo "                                </li>\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <!-- /STEPS -->\n";
echo "            <!-- FORM -->\n";
echo "            <div class=\"col-lg-8\">\n";
echo "                <div class=\"card border-dark shadow bg-body rounded-3\" style=\"margin-bottom: 30px\">\n";
echo "                    <div class=\"card-body\">\n";
echo "                        <form>\n";
echo "                            <div class=\"mt-3 row row-cols-lg-auto g-3\" style=\"margin-top: 5px !important;\">\n";
echo "                                <div class=\"col-12 mt-5\">\n";
echo "                                    <div class=\"step-number step-form \">\n";
echo "                                        <span class=\"step-number-content\" style=\"width: 40px !important;\">1</span>\n";
echo "                                    </div>\n";
echo "                                    <p class=\"visible992 step-title\">\n";
echo "                                        Tell us who to thank and select an amount of support.\n";
echo "                                    </p>\n";
echo "                                    <label class=\"visually-hidden\" for=\"first_name\">Name</label>\n";
echo "                                    <div class=\"input-group\"\n";
echo "                                    \">\n";
echo "                                    <div class=\" input-group-text\">Name</div>\n";
echo "                                    <input class=\"form-control\" id=\"first_name\" name=\"first_name\" type=\"text\">\n";
echo "                                </div>\n";
echo "                                <div class=\"row error-handling\">\n";
echo "                                    <span>error</span>\n";
echo "                                </div>\n";
echo "                                <label class=\"visually-hidden\" for=\"last_name\">Last Name</label>\n";
echo "                                <div class=\"input-group\">\n";
echo "                                    <div class=\"input-group-text\">Last Name</div>\n";
echo "                                    <input class=\"form-control\" id=\"last_name\" name=\"last_name\" type=\"text\">\n";
echo "                                </div>\n";
echo "                                <div class=\"row error-handling\">\n";
echo "                                    <span>error</span>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"mb-3\">\n";
echo "                        <label class=\"form-label\" for=\"amount\">Contribute amount:</label>\n";
echo "                        <ul class=\"list-group list-group-horizontal d-flex justify-content-between\">\n";
echo "                            <li class=\"list-group-item\">\n";
echo "                                <button class=\"btn btn-outline-primary\" type=\"button\">USD$ 20</button>\n";
echo "                            </li>\n";
echo "                            <li class=\"list-group-item\">\n";
echo "                                <button class=\"btn btn-outline-primary\" type=\"button\">USD$ 40</button>\n";
echo "                            </li>\n";
echo "                            <li class=\"list-group-item\">\n";
echo "                                <button class=\"btn btn-outline-primary\" type=\"button\">USD$ 60</button>\n";
echo "                            </li>\n";
echo "                            <li class=\"list-group-item\">\n";
echo "                                <button class=\"btn btn-outline-primary\" type=\"button\">USD$ 80</button>\n";
echo "                            </li>\n";
echo "                            <li class=\"list-group-item\">\n";
echo "                                <button class=\"btn btn-outline-primary\" type=\"button\">USD$ 100</button>\n";
echo "                            </li>\n";
echo "                        </ul>\n";
echo "                        <div class=\"input-group mt-2 col-lg-12\">\n";
echo "                            <span class=\"input-group-text\">USD$</span>\n";
echo "                            <input class=\"form-control\" id=\"amount\" name=\"amount\" type=\"text\">\n";
echo "                            <button class=\"btn btn-outline-primary\" type=\"button\">USD/CAD</button>\n";
echo "                            <small class=\"col-lg-12 textMargin992\">Custom\n";
echo "                                <amount></amount>\n";
echo "                            </small>\n";
echo "                        </div>\n";
echo "                        <div class=\"error-handling\">\n";
echo "                            <span>error</span>\n";
echo "                        </div>\n";
echo "                        <div class=\" step-number step-form step-form-two button-top\" style=\"margin-top: 15px;\">\n";
echo "                            <span class=\"step-number-content\" style=\"width: 40px !important;\">2</span>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <hr class=\"hr\">\n";
echo "                    <p class=\"visible992 marginTop992 step-title \">\n";
echo "                        Choose what U would like to support.\n";
echo "                    </p>\n";
echo "                    <!––>\n";
echo "                    <div class=\"mb-3 mt-5 marginDelete992 delete992\">\n";
echo "                    </div>\n";
echo "\n";
echo "                    <div class=\"mb-3 mt-5 marginDelete992\">\n";
echo "                        <label class=\"form-label\" for=\"category\" style=\"margin-top:15px; Delete992\">To the following\n";
echo "                            Building-u initiative(s)</label>\n";
echo "                        <label class=\"container10\"> Support Building-U resources and student outreach\n";
echo "                            <input type=\"checkbox\">\n";
echo "                            <span class=\"checkmark\"></span>\n";
echo "                        </label>\n";
echo "\n";
echo "                        <label class=\"container10\">Fund scholarships awarded at $4YT\n";
echo "                            <input type=\"checkbox\">\n";
echo "                            <span class=\"checkmark\"></span>\n";
echo "                        </label>\n";
echo "\n";
echo "                        <label class=\"container10\">Support our internship programs\n";
echo "                            <input type=\"checkbox\">\n";
echo "                            <span class=\"checkmark\"></span>\n";
echo "                        </label>\n";
echo "                    </div>\n";
echo "                    <hr class=\"hr\">\n";
echo "                    <div class=\"step-number step-form step-form-three mb-3 button-top\">\n";
echo "                        <span class=\"step-number-content\" style=\"width: 40px !important;\">3</span>\n";
echo "                    </div>\n";
echo "                    <p class=\"visible992 marginTop992 step-title\">\n";
echo "                        Enter your card details and submit!\n";
echo "                    </p>\n";
echo "                    <br>\n";
echo "                    <div class=\"mb-3 mt-4 marginDelete992\">\n";
echo "                        <div class=\"input-group marginDelete992\" style=\"margin-top: 30px;\">\n";
echo "                            <span class=\"input-group-text\">Visa</span>\n";
echo "                            <input class=\"form-control\" id=\"card\" name=\"card\" placeholder=\"Your card number\"\n";
echo "                                   type=\"text\">\n";
echo "                        </div>\n";
echo "                        <div class=\"error-handling\">\n";
echo "                            <span>error</span>\n";
echo "                        </div>\n";
echo "                        <label class=\"visually-hidden\" for=\"expire_date\">Expire Date</label>\n";
echo "                        <div class=\"input-group\">\n";
echo "                            <div class=\"input-group-text\">EXP</div>\n";
echo "                            <input class=\"form-control\" id=\"expire_date\" name=\"expire_date\" placeholder=\"mm/YYYY\"\n";
echo "                                   type=\"text\">\n";
echo "                            <small class=\"col-lg-12 textMargin992\">Expire date</small>\n";
echo "                        </div>\n";
echo "                        <div class=\"error-handling\">\n";
echo "                            <span>error</span>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"mb-3 row row-cols-lg-auto g-3\">\n";
echo "                        <div class=\"col-6\">\n";
echo "                            <label class=\"visually-hidden\" for=\"cvv\">CVV</label>\n";
echo "                            <div class=\"input-group\">\n";
echo "                                <div class=\"input-group-text\">CVV</div>\n";
echo "                                <input class=\"form-control\" id=\"cvv\" name=\"cvv\" type=\"text\">\n";
echo "                            </div>\n";
echo "                            <div class=\"error-handling\">\n";
echo "                                <span>error</span>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <hr class=\"hr\">\n";
echo "                    <div class=\"step-number step-form step-form-three mb-3 button-top\">\n";
echo "                        <span class=\"step-number-content\" style=\"width=40px !important;\">4</span>\n";
echo "                    </div>\n";
echo "                    <p class=\"visible992 marginTop992 step-title\">\n";
echo "                        Would you like for this to be a gift?\n";
echo "                    </p>\n";
echo "                    <div class=\"mb-3 mt-4 marginDelete992\">\n";
echo "                        <label class=\"form-label delete992\" for=\"category\" style=\"margin-top:30px; visible992\">Would you\n";
echo "                            like for this to be a gift?</label>\n";
echo "\n";
echo "\n";
echo "                        <label class=\"container10\"> Yes\n";
echo "                            <input id=\"inputEmailCheckbox\" onclick=\"inputEmail()\" type=\"checkbox\">\n";
echo "                            <span class=\"checkmark\"></span>\n";
echo "                        </label>\n";
echo "                    </div>\n";
echo "\n";
echo "\n";
echo "                    <div class=\"input-group marginDelete992\" id=\"inputEmailInput\" style=\"display:none\">\n";
echo "                        <div class=\"input-group marginDelete992\">\n";
echo "                            <span class=\"input-group-text\">Email</span>\n";
echo "                            <input class=\"form-control\" id=\"card\" name=\"card\" placeholder=\"Recipient's email\"\n";
echo "                                   type=\"text\">\n";
echo "                        </div>\n";
echo "\n";
echo "                    </div>\n";
echo "\n";
echo "                    <div class=\"row d-flex justify-content-end\">\n";
echo "\n";
echo "\n";
echo "                        <center>\n";
echo "                            <button class=\"btn btn-primary col-lg-3 me-3 mt-4 mb-2\n";
echo "                            button992\"\n";
echo "                                    style=\"background-color:#5FC5FF !important; border-color: #5FC5FF !important; font-weight: bold; padding-top: 10px; padding-bottom: 10px; width: 350px;\"\n";
echo "                                    type=\"submit\">DONATE\n";
echo "                            </button>\n";
echo "                        </center>\n";
echo "                        <center><small style=\"font-size: 1em;font-weight: bold; \">After your donation of <span\n";
echo "                                style=\"color: red\">money</span>, you will\n";
echo "                            receieve <span style=\"color: red\">amount </span>U-Points!\n";
echo "\n";
echo "                        </small></center>\n";
echo "                    </div>\n";
echo "                    </form>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</div>\n";
echo "</div>\n";
echo "\n";
echo "\n";
?>
<script crossorigin="anonymous"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
