<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <title></title>\n";
echo "    <meta charset=\"UTF-8\"/>\n";
echo "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"/>\n";
echo "    <link href=\"shopping-item.css\" rel=\"stylesheet\"/>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<div class=\"shop-title\">\n";
echo "    <div class=\"title-wrapper\">\n";
echo "        <h1>The U-SHOP</h1>\n";
echo "    </div>\n";
echo "</div>\n";
echo "<div class=\"container\">\n";
echo "    <div class=\"image\">\n";
echo "        <div class=\"img\">\n";
echo "            <img alt=\"tshirt\"\n";
echo "                 src=\"https://images.vexels.com/media/users/3/142546/isolated/preview/2f6d0faa355125320122dc57e8b07084-tshirt-icon-by-vexels.png\"\n";
echo "                 style=\"background-color: lightgray;\"/>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "    <div class=\"description\">\n";
echo "\n";
echo "        <div class=\"selector-wrapper\">\n";
echo "            <div class=\"item-title\">\n";
echo "                <h1 style=\" margin: 0;font-size: 3rem;\">\n";
echo "                    <strong>Bubble Tee</strong>\n";
echo "                </h1>\n";
echo "                <h3 style=\"margin: 0; font-size: 1.5rem;\">20</h3>\n";
echo "            </div>\n";
echo "            <div class=\"selector\">\n";
echo "                <form class=\"customize-panel\">\n";
echo "                    <h3>Color</h3>\n";
echo "                    <input checked id=\"red\" name=\"color\" type=\"radio\" value=\"red\">\n";
echo "                    <label for=\"red\"> Red</label>\n";
echo "                    <input checked id=\"blue\" name=\"color\" type=\"radio\" value=\"blue\">\n";
echo "                    <label for=\"blue\"> blue</label>\n";
echo "                    <h3>Size</h3>\n";
echo "                    <input checked id=\"small\" name=\"color\" type=\"radio\" value=\"small\">\n";
echo "                    <label for=\"small\"> Small</label>\n";
echo "                    <input checked id=\"medium\" name=\"color\" type=\"radio\" value=\"medium\">\n";
echo "                    <label for=\"medium\"> medium</label>\n";
echo "                    <input checked id=\"medium\" name=\"color\" type=\"radio\" value=\"medium\">\n";
echo "                    <label for=\"large\"> large</label>\n";
echo "                    <h3>Quanitity: </h3>\n";
echo "                    <label for=\"Quantity\"></label>\n";
echo "                    <input class=\"slider\" id=\"quanititySlider\" max=\"10\" min=\"1\" type=\"number\" value=\"1\">\n";
echo "                    <input class=\"submit-button\" type=\"submit\" value=\"Add to Cart!\"/>\n";
echo "                </form>\n";
echo "                <input class=\"submit-button\" id=\"go-back\" onclick=\"history.back()\" type=\"button\" value=\"Go Back\"/>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</div>\n";
echo "</body>\n";
echo "\n";
echo "</html>";

?>
